# Generated by Django 3.1.2 on 2021-06-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210611_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat5',
            new_name='cat3',
        ),
    ]
