# Generated by Django 3.1.2 on 2021-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210611_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat5',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
